# Generated by Django 3.2.7 on 2021-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_serviceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='name',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
